package automod_legacy

// These words are listed in in alphabethical order.
var BuiltinSwearWords = map[string]bool{
    "ballsack":    true,
    "bollock":     true,
    "bollok":      true,
    "clitoris":    true,
    "cunt":        true,
    "dyke":        true,
    "erection":    true,
    "fag":         true,
    "faggot":      true,
    "fellate":     true,
    "fellatio":    true,
    "felching":    true,
    "fudgepacker": true,
    "genitals":    true,
    "knobend":     true,
    "labia":       true,
    "muff":        true,
    "nigger":      true,
    "nigga":       true,
    "pube":        true,
    "scrotum":     true,
    "slut":        true,
    "spunk":       true,
    "tranny":      true,
    "trannies":    true,
    "tosser":      true,
    "wank":        true,
}
